name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: Bia-Gs
          outputs: |
            dist/snake.svg?color_snake=FF00F6&color_dots=#000000,#000000,#080808,#141414,#1f1f1f
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
